server:
  port: 8081

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/buy01_users

eureka:
  client:
    enabled: false

jwt:
  secret: change-this-to-a-long-random-dev-secret
  expiration: 86400000