services:
  mongo:
    image: mongo:7
    container_name: buy01-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 15s

  user-service:
    build:
      context: ./user-service   # path to the folder containing this Dockerfile + pom.xml
    container_name: buy01-user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/buy01_users
      JWT_SECRET: ${JWT_SECRET:-dev-only-change-me-please-make-me-long-and-random}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongo-data:
