spring:
  application:
    name: MEDIA-SERVICE

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: 0123456789abcdef0123456789abcdef0123456789abcdef
  expiration: 86400000

media:
  storage:
    location: uploads/images