spring:
  application:
    name: product-service   # this exact name is how the gateway will find it
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET:change-this-to-a-long-random-dev-secret-plus-long-for-bits256length}
eureka:
  client:
    disabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082   # random port — Eureka handles discovery, so hardcoding a port is pointless